### ISSUE TITLE
Gradients of substitution model parameters

### ISSUE THREAD

**Issue by christiaanjs** [phylovi/libsbn#105]
The current Beagle interface only provides gradients of the likelihood with respect to branch lengths. To do inference on substitution model parameters we would like gradients of the likelihood with respect to those parameters.

Gradients of substitution model parameters can be calculated by summing a function of the post- and pre-order partials over branches, as described in [Schadt et al 1998, Computational Advances in Maximum Likelihood Methods for Molecular Phylogeny](https://genome.cshlp.org/content/8/3/222.long)

This is described nicely in matrix-vector language in [Ji et al 2019, Gradients do grow on trees](https://arxiv.org/abs/1905.12146)

My expansion of the notation in that paper (for individual transition probabilities):

![substitution-gradient](https://user-images.githubusercontent.com/12289509/65006668-e3dffc00-d957-11e9-8708-3d648b1e52a7.PNG)

Reducing the above expression over branches could be nicely handled by the preorder traversal higher order function already implemented.

I suggest we could provide gradients with respect to either the eigendecomposition of the substitution model rate matrix and/or the branch transition probabilities.

**Comment by christiaanjs** [comment]
I'm happy to have a go implementing this in libsbn by accessing Beagle partials. Otherwise, it could be accomplished with the [`hmc-clock` branch of Beagle](https://github.com/beagle-dev/beagle-lib/tree/hmc-clock) as in [BEAST](https://github.com/beast-dev/beast-mcmc/blob/7c4d2ed4c4784e486b686b0fca05e9ecf9d97329/src/dr/evomodel/treedatalikelihood/preorder/AbstractDiscreteTraitDelegate.java)

**Comment by matsen** [comment]
Awesome! 

Because Mathieu is using @xji3's method for calculating gradients of time-tree node-height proportions, we'll be using `hmc-clock` anyhow. So I would much prefer if you went that route.

(ps. sorry for the slow response-- it's not from lack of enthusiasm, but I blocked yesterday to write)
