### ISSUE TITLE
Gradients using the hmc-clock branch in Beagle

### ISSUE THREAD

**Issue by 4ment** [phylovi/libsbn#106]
Currently libsbn uses the master branch of beagle to calculate the gradient of the branch lengths. The branch hmc-clock contains some new functions that make it easier to calculate the gradient.
Once we've got an implementation for the derivatives wrt branch lengths, the plan is to use the same functions with the chain rule to calculate the derivatives wrt to heights and/or the ratios involved in the reparameterization of the node heights. The same functions can also be used for calculating the gradient of other parameters such as GTR, substitution rate, rate heterogeneity...

**Comment by matsen** [comment]
* Need to store model information in a SubstitutionModel interface
    * QMatrix
    * NTFrequencies
    * QGradients
* Store this inside a LikelihoodCalculator class
    * BeagleInstance
    * PatternCount

**Comment by matsen** [comment]
Comments from CS on https://github.com/phylovi/libsbn/pull/107#discussion_r329808376

**Comment by matsen** [comment]
The model interface moved to https://github.com/phylovi/libsbn/issues/131 .
