### ISSUE TITLE
Fixes to make things work on EBOV data

### ISSUE THREAD

**Issue by matsen** [phylovi/libsbn#151]
So far, need to throw away degenerate nucleotides.

**Comment by matsen** [comment]
@4ment I added a bunch of things to the symbol table so it looks like this: 

                    {'-', 4},
                    {'N', 4},
                    {'X', 4},
                    {'?', 4},
                    // Treat degenerate nucleotides as gaps.
                    {'K', 4},
                    {'M', 4},
                    {'R', 4},
                    {'U', 4},
                    {'W', 4},
                    {'Y', 4}});


But in the end it'd be better to translate everythings to gaps first and then compress the alignment. Perhaps this doesn't make the cut for "worthwhile" or perhaps it makes the todo list somewhere.

**Comment by 4ment** [comment]
What about using `beagleSetTipPartials` instead of `beagleSetTipStates` for degenerate nucleotides? For example, for R it would be 1,0,1,0 if A and G are encoded as 1,0,0,0 and 0,0,1,0.

**Comment by matsen** [comment]
Oh, that's a much better solution.
