### ISSUE TITLE
Deal with quotes in Newick trees

### ISSUE THREAD

**Issue by 4ment** [phylovi/libsbn#191]
The current Newick parser keeps double quotes in taxon names causing problems when matching taxon names to sequence names.

By convention quotes are used to preserve underscores in taxon names, otherwise underscores are replaced by spaces. The FASTA format does not follow this rule so sequence names can have underscores without quotes.

Quotes could be completely ignored or if they are not present replace underscores with spaces to comply with the Newick format specification.

Dendropy has options to deal with this rule (i.e. `preserve_underscores=True`, `unquoted_underscores =True`)

Source:
http://evolution.genetics.washington.edu/phylip/newick_doc.html

**Comment by matsen** [comment]
My personal sense is that this stuff is an anachronism. Who puts in underscores when they mean spaces? If you really want spaces, quote your strings. 

Here's a proposal.

## Parsing:

* Quotation marks are always removed, and an error is thrown if quotation marks are not matching.
* Single quotation marks can be protected using single quotation marks in a quoted string.

* If `preserve_underscores` is True (default) then underscores are kept even if they aren't quoted.
* If `preserve_underscores` is False, then underscores in unquoted labels are replaced with spaces.

## Writing:

I propose having only one switch, which is `quote_labels`, which is off by default. If this is flipped on, then all labels are expressed with quotes. DendroPy has `unquoted_underscores` and `preserve_spaces`, which seems overly confusing.

## Questions:

1. The Newick standard says that whitespace in unquoted taxon names should fail to parse. Do we want to do the same?
2. The standard says `' string_of_printing_characters '` as a definition of a quoted label, although the examples I've seen have double quotes (`"`) and no space. Should we treat single and double quotes the same?

**Comment by matsen** [comment]
New proposal: just remove single and double quotes. That's all.
