### ISSUE TITLE
DAG implementation

### ISSUE THREAD

**Issue by junseonghwan** [phylovi/libsbn#216]
For implementation of likelihood EM algorithm, we are using a DAG structure and traversal on DAG. We will keep implementation notes here.

The description of the data structures are found in #213. We need to determine the node/edge visitation order for rootward and leafward passes.

Concepts:
- Subsplits are the nodes of DAG (referred to osbusplit in the manuscript).
- Edges are given by the PCSPs.

**Comment by junseonghwan** [comment]
`DAGNode` class will be created, which holding 4 vectors:
- `leafward_rotated`
- `leafward_sorted`
- `rootward_rotated`
- `rootward_sorted`
Each of these vectors is going to store PCSP index. The PCSP index can be used to retrieve branch length and SBN parameters.

We don't need to create a new class to represent the edges as the edges are given by PCSP index.

The `nodes` vector will be created to store the nodes. This vector is to be indexed the same way as `plv`. That is, `plv[idx]` is the plv for `node[idx]`.

**Comment by matsen** [comment]
Sounds great! 

Don't forget the convention that member variables have a trailing underscore.
