### ISSUE TITLE
Expose a ratio gradient for TensorFlow

### ISSUE THREAD

**Issue by matsen** [phylovi/libsbn#219]
To enable a [TensorFlow custom gradient](https://www.tensorflow.org/api_docs/python/tf/custom_gradient) something like 

```python
# https://github.com/christiaanjs/treeflow/blob/master/treeflow/beagle.py#L48
@tf.custom_gradient
def ratio_gradient(x):
    heights = tf.numpy_function(forward_transform, [x], [tf.float32])
    def grad(dy):  # dy is gradient of something WRT node heights
        # Here we transform back to ratio-land.
        return tf.numpy_function(ratio_gradient, [dy], [tf.float32])
    return heights, grad
```

**Comment by matsen** [comment]
Factor out everything after https://github.com/phylovi/libsbn/blob/a0f1aa94edc0006b51234dd7e0663c08bd95a477/src/fat_beagle.cpp#L491 as method of RootedTree, but but where you can supply height_gradient as an argument.

* Input: each element has one entry per node height
* Output: one gradient for every ratio

For now, assume we aren't going to call the outer function multiple times before calling the inner function. Assume the heights won't change before we call the second function.

**Comment by christiaanjs** [comment]
This is meant to replace the Tensorflow implementation in treeflow: https://github.com/christiaanjs/treeflow/blob/master/treeflow/tree_transform.py#L21
