### ISSUE TITLE
Some compilation issues that we may want to address ...

### ISSUE THREAD

**Issue by msuchard** [phylovi/libsbn#226]
1. `libsbn` appears to rely on a pre-release of `Eigen` v3.4 and does not compile (in my hands) with v3.3.

**Comment by msuchard** [comment]
2. We need some backwards compatibility to mac os 10.13 (because it still works with NVIDIA GPUs).  On 10.13, I get this compilation error:
```
_build/gp_engine.cpp:89:5: error: call to unavailable function 'visit': introduced in macOS 10.14
```

**Comment by msuchard** [comment]
3. And this:
```
/Users/msuchard/.pyenv/versions/3.7.3/lib/python3.7/site-packages/pybind11/include/pybind11/detail/common.h:112:10: fatal error: 
      'Python.h' file not found
#include <Python.h>
```

**Comment by matsen** [comment]
Thanks for this, @msuchard !

Regarding 1, the Eigen gets pulled down as part of the git submodule system. Do you not like that approach?

**Comment by msuchard** [comment]
I love `git submodule`.   Will figure out why that didn't work for me, as I did try a `git submodule update`.

**Comment by matsen** [comment]
I think I should have put `git submodule init` too. We could put 

    git submodule --init --recursive

in the docs.

**Comment by 4ment** [comment]
The eigen submodule points to a GitHub repo which is now deprecated. It would be good to use the new gitlab repo at some point

**Comment by matsen** [comment]
Thanks, @4ment I have changed that now.

@msuchard , did you get past 3. by using conda?

**Comment by msuchard** [comment]
Yep.

**Comment by matsen** [comment]
OK. I think we're sorted with this then. Feel free to re-open if you don't agree.
