### ISSUE TITLE
Add uniform topology prior for generalized pruning 

### ISSUE THREAD

**Issue by matsen** [phylovi/libsbn#234]

**Comment by matsen** [comment]
![image](https://user-images.githubusercontent.com/112708/87157419-15251200-c273-11ea-94d3-2c56e6573f10.png)

**Comment by matsen** [comment]
It would also be nice to have a `GenerateAllTrees` as a GPInstance method: generate all of the trees in the SBN support and save them to a file.

**Comment by junseonghwan** [comment]
Write function to sample a tree in `GPInstance` similarly to `SBNInstance::SampleTopology`. This will help with testing the implementation of uniform prior.
