### ISSUE TITLE
page faults dominating runtime for the generalized pruning algorithm

### ISSUE THREAD

**Issue by matsen** [phylovi/libsbn#237]
## Summary

The generalized pruning algorithm allows us to cache a lot of intermediate results, and indeed requires caching of a lot of intermediate results. We can store those intermediate results in a big block of memory. This should allow it to be fast. However, right now the runtime of the algorithm appears to be dominated by page faults on that big block.

We have designed our implementation of this algorithm to be as "predictable" as possible, and my hope was that this would allow for pre-fetching, so that we wouldn't have this problem. However, that doesn't appear to be the case.

## Steps to reproduce problem

* compile libsbn `216-DAG-implementation` branch with `make` (which should install `libsbn` as a Python package to your conda environment)
* clone https://github.com/matsengrp/gp-experiments
* check that you are in the libsbn conda environment (`conda activate libsbn` if not)
* do additional install steps as specified in the README for that repo
* go to `experiments/2020-07-11-frozen`
* to run `perf stat` use the script `./stat.sh` (takes a few minutes)
* to run `perf record` use the script `./record.sh` (takes the same amount of time)

## Evidence that page faults are a problem

From `perf stat`
```
      49573.899415      task-clock (msec)         #    0.953 CPUs utilized          
             7,465      context-switches          #    0.151 K/sec                  
                 2      cpu-migrations            #    0.000 K/sec                  
        18,003,315      page-faults               #    0.363 M/sec                  
   162,242,849,745      cycles                    #    3.273 GHz                    
   184,631,438,640      instructions              #    1.14  insn per cycle         
    14,922,882,092      branches                  #  301.023 M/sec                  
        56,342,781      branch-misses             #    0.38% of all branches        

      52.043842016 seconds time elapsed
```

Using `perf report` it looks to me like everything is about memory mapping: 

![image](https://user-images.githubusercontent.com/112708/87244288-ff3d5b80-c3f0-11ea-88f7-da4555ec50e6.png)

## A bit more detail

Why did I hope that pre-fetching would save us here? We designed the algorithm to first compute all of the steps it must take, and then execute them. 

Specifically, we 

* express the operations needed in terms of a vector of [GPOperation](https://github.com/phylovi/libsbn/blob/216-DAG-implementation/src/gp_operation.hpp)s. These are simple structs holding indices.
* to execute those operations, we give them to a [GPEngine](https://github.com/phylovi/libsbn/blob/216-DAG-implementation/src/gp_engine.cpp#L31) that executes them in terms of relatively simple Eigen library operations.
* we can see this put into practice [here](https://github.com/phylovi/libsbn/blob/216-DAG-implementation/src/gp_instance.cpp#L121), which is the code called by the experiment. We first make a `compute_likelihoods_operations` vector, and then process it, [which simply applies std::visit to each of the operations](https://github.com/phylovi/libsbn/blob/216-DAG-implementation/src/gp_engine.cpp#L90)

Although I haven't looked at assembly, I thought that the strategy of boiling execution down to a big vector of indexing structs and then going through them would keep branching to an absolute minimum, enabling pre-fetching. 

## Next steps

I would like to try using a usual memory allocation rather than [the call to mmap](https://github.com/phylovi/libsbn/blob/216-DAG-implementation/src/mmapped_matrix.hpp#L45)

I tried @rigtorp's [suggestion to use `MAP_LOCKED`](https://rigtorp.se/virtual-memory/), but this led to an immediate segfault. Here's what I tried:

```diff
+++ b/src/mmapped_matrix.hpp
@@ -46,9 +46,9 @@ class MmappedMatrix {
         NULL,                    // This address is ignored as we are using MAP_SHARED.
         mmap_len_,               // Size of map.
         PROT_READ | PROT_WRITE,  // We want to read and write.
-        MAP_SHARED,              // We need MAP_SHARED to actually write to memory.
-        file_descriptor_,        // File descriptor.
-        0                        // Offset.
+        MAP_SHARED | MAP_LOCKED | MAP_POPULATE,
+        file_descriptor_,  // File descriptor.
+        0                  // Offset.
     );
   }
```

**Comment by matsen** [comment]
@ognian- asked an excellent question-- could the page faults be somewhere else? 

I did a check which says "no."

Here are two runs with the commited code in the `216-DAG-implementation` of libsbn:

```
        17,919,067      page-faults               #    0.488 M/sec
        17,919,078      page-faults               #    0.489 M/sec                  
```

Now, if I add an early return _after_ doing all of the tree processing and operation creation but _before_ doing anything with my mmap-ed memory, we get:

```diff
diff --git a/src/gp_instance.cpp b/src/gp_instance.cpp
index a3897d7..0fd8cd3 100644
--- a/src/gp_instance.cpp
+++ b/src/gp_instance.cpp
@@ -109,6 +109,7 @@ void GPInstance::EstimateBranchLengths(double tol, size_t max_iter) {
   GPOperationVector compute_likelihoods_operations = dag_.ComputeLikelihoods();
   GPOperationVector branch_optimization_operations = dag_.BranchLengthOptimization();
   GPOperationVector marginal_lik_operations = dag_.MarginalLikelihood();
+  return;
 
   ProcessOperations(dag_.SetRootwardZero());
   ProcessOperations(dag_.SetLeafwardZero());
```

With this we get orders of magnitude fewer page faults:

```
            81,847      page-faults               #    0.094 M/sec
```

So, it's the GPOperation processing.

**Comment by rigtorp** [comment]
There is a bug here: https://github.com/phylovi/libsbn/blob/216-DAG-implementation/src/mmapped_matrix.hpp#L45

You need to check the return value:
```
if (!ptr) {
  throw std::system_error(errno, std::system_category(), "mmap");
}
```

**Comment by matsen** [comment]
Thanks, @rigtorp !

Added in 4bf115c3ac68f0c5740325c70ed28191ead63297

**Comment by matsen** [comment]
Before changing:

```
         34,931.31 msec task-clock                #    0.979 CPUs utilized
             5,262      context-switches          #    0.151 K/sec
                78      cpu-migrations            #    0.002 K/sec
        17,929,629      page-faults               #    0.513 M/sec
   154,880,169,651      cycles                    #    4.434 GHz
   190,270,085,462      instructions              #    1.23  insn per cycle
    16,082,649,790      branches                  #  460.408 M/sec
        51,776,000      branch-misses             #    0.32% of all branches

      35.690998748 seconds time elapsed
      17.761318000 seconds user
      17.205868000 seconds sys
```

after changing to @ognian-'s version:

```cpp
void GPEngine::operator()(const GPOperations::Likelihood& op) {
     SetTransitionMatrixToHaveBranchLength(branch_lengths_(op.dest_idx));
     log_likelihoods_[op.dest_idx] = log(q_[op.dest_idx]) +
         ((EigenVectorXd)((
         plvs_.at(op.parent_idx).transpose() * (transition_matrix_ * plvs_.at(op.child_idx))
         ).diagonal().array().log()))
         .dot(site_pattern_weights_);
}

```

```
          1,851.07 msec task-clock                #    0.806 CPUs utilized          
                97      context-switches          #    0.052 K/sec                  
                 1      cpu-migrations            #    0.001 K/sec                  
            81,850      page-faults               #    0.044 M/sec                  
     7,560,949,551      cycles                    #    4.085 GHz                    
    12,705,529,714      instructions              #    1.68  insn per cycle         
     1,720,453,541      branches                  #  929.439 M/sec                  
        20,853,419      branch-misses             #    1.21% of all branches        

       2.295707876 seconds time elapsed

       1.662059000 seconds user
       0.191045000 seconds sys
```

Here's a version which does keep our assignment to `per_pattern_log_likelihoods_`:
```diff
diff --git a/src/gp_engine.cpp b/src/gp_engine.cpp
index e650a15..440f4fb 100644
--- a/src/gp_engine.cpp
+++ b/src/gp_engine.cpp
@@ -63,9 +63,11 @@ void GPEngine::operator()(const GPOperations::Multiply& op) {
 
 void GPEngine::operator()(const GPOperations::Likelihood& op) {
   SetTransitionMatrixToHaveBranchLength(branch_lengths_(op.dest_idx));
-  auto result = plvs_.at(op.parent_idx).transpose() *
-                (transition_matrix_ * plvs_.at(op.child_idx));
-  per_pattern_log_likelihoods_ = result.diagonal().array().log();
+  per_pattern_log_likelihoods_ =
+      (plvs_.at(op.parent_idx).transpose()(transition_matrix_ * plvs_.at(op.child_idx)))
+          .diagonal()
+          .array()
+          .log();
   log_likelihoods_[op.dest_idx] =
       log(q_[op.dest_idx]) + per_pattern_log_likelihoods_.dot(site_pattern_weights_);
 }
```

this version is just as fast:

```
          1,867.60 msec task-clock                #    0.806 CPUs utilized
                96      context-switches          #    0.051 K/sec
                 2      cpu-migrations            #    0.001 K/sec
            81,841      page-faults               #    0.044 M/sec
     7,533,731,730      cycles                    #    4.034 GHz
    12,705,923,724      instructions              #    1.69  insn per cycle
     1,720,500,556      branches                  #  921.234 M/sec
        20,782,430      branch-misses             #    1.21% of all branches

       2.317430676 seconds time elapsed

       1.656831000 seconds user
       0.212594000 seconds sys
```

Thank you, Ognian! 

I'm going to go eliminate all temporaries in these functions, which in retrospect we should have done previously-- Eigen has lots of templating magic to make complex calls fast.
