### ISSUE TITLE
Add root node to DAG

### ISSUE THREAD

**Issue by matsen** [phylovi/libsbn#273]
This is the continuation of #247. In that work, we moved to the "compact" representation of PCSPs.

However, I didn't change the rootsplits because we didn't have to, and because we may want to sip some tea and reconsider how rootsplits are expressed in the rest of the code. 

@mdkarcher has pointed out that we might be able to have less special purpose code by encoding rootsplits like 

    00000|11111|00111

**Comment by matsen** [comment]
Code duplication marked with `#273`.

**Comment by matsen** [comment]
Also, note that we will want to think about the role of fake subsplits. Right now these aren't handled by IndexerRepresentationOf... perhaps we'd like to do that?

**Comment by matsen** [comment]
Can we drop the indexer object altogether and instead equip the edges of the DAG with GPCSP indices?

**Comment by matsen** [comment]
Note (cc @shokiami @annakooperberg ) that we can drop the G of "GPCSP" with this commit because everything is just a PCSP.

**Comment by annakooperberg** [comment]
This issue flips the rotation of rootsplits which changes the indexing of the DAGs represented by previous images in https://github.com/phylovi/libsbn/issues/323. For example, the `five_taxon_rooted_more_2.nwk ` now looks like:

![output](https://user-images.githubusercontent.com/12280254/126843373-f1904407-11e6-46ce-abc8-524f7d339d93.png)

In general, to create a dot file for a DAG, run the simple python script:

```
import libsbn
import os

# Set working directory to your libsbn directory location
os.chdir(os.path.join(os.environ["HOME"], 'libsbn'))

mmap_file_path = '_ignore/mmapped_plv.data'
fasta_file = 'data/five_taxon.fasta'
newick_file = 'data/five_taxon_rooted_more_2.nwk'
out_file = '_ignore/out.dot'

inst = libsbn.gp_instance(mmap_file_path)
inst.read_fasta_file(fasta_file)
inst.read_newick_file(newick_file)
inst.make_engine()
inst.subsplit_dag_to_dot(out_file, True)
```
and an image can be generated from a dot file using the command: `dot _ignore/out.dot -Tpng -o output.png`.
