### ISSUE TITLE
Tree parsing issues

### ISSUE THREAD

**Issue by 4ment** [phylovi/libsbn#277]
Some issues I have noticed:

Programs include comments inside a newick tree file in different ways. Currently libsbn parses `(A:[&date=1]0.1, B:1)` correctly but it does not work on `(A[&date=1]:0.1, B:1)`

In some cases we can provide a topology for the purpose of estimating a time tree. Libsbn expects the branches to represent time (e.g. ultrametric) so it will fail if the time constraints are not satisfied. Can we remove this check? or make it optional?

For now libsbn decides if sequences are homochronous or heterochronous by looking at the end of the taxon names. For example `A/flu/abcd_2001` is considered to be heterochronous because there is a valid "date" after the last underscore. Unfortunately some sequences can end with an underscore followed by random numbers. We need another mechanism to provide dates. It could be custom block in a nexus file, a csv file, or a switch to let know libsbn that dates are included in the taxon names

**Comment by matsen** [comment]
Progress in https://github.com/phylovi/libsbn/compare/277-tree-parsing

Question: What do we want the behavior to be if we don't provide any dates? Do we want failures for other components of the code? Right now the code segfaults when we ask for a gradient.

Regarding time constraints, this has to do if we want to run "InitializeParameters". I don't think that calling this makes sense if we don't have a time-constrained tree, right? We can avoid calling it, but I want to be careful of making a clean API.
