### ISSUE TITLE
What to do with error handling?

### ISSUE THREAD

**Issue by matsen** [phylovi/libsbn#5]
So far I've been using printing and `abort()`. 

I think I'll start just throwing naked exceptions. I don't see a clear reason to [wrap exceptions as RB does](https://github.com/revbayes/revbayes/blob/94149b1bc5067b4ffa06ee132b89b91baf4233f5/src/core/utils/RbException.cpp).

**Comment by matsen** [comment]
Going to use exceptions. When we make the switch, don't forget to drop the corresponding iostream includes.

**Comment by matsen** [comment]
Can we have the messages available in Jupyter?

**Comment by christiaanjs** [comment]
Pybind documentation on redirecting `std::cerr` and `std::cout` to Python: https://pybind11.readthedocs.io/en/stable/advanced/pycpp/utilities.html#capturing-standard-output-from-ostream

**Comment by matsen** [comment]
Closed by https://github.com/phylovi/libsbn/commit/93cf7b6d14739e853346b14efe17efccba17b977
