### ISSUE TITLE
Add contributors list

### ISSUE THREAD

**Issue by matsen** [phylovi/libsbn#76]
Hello everyone-- it's time to acknowledge all of your contributors.

Shall we move development to a separate organization? If so, what shall we name it? 

My suggestion would be `viphylo` or `variationalphylo`. Or perhaps `VariationalPhylo`? Ideas? Votes?

**Comment by matsen** [comment]
I like `varinphy`.

**Comment by matsen** [comment]
OK, now I like `phylovi`, at http://phylovi.org/, called "The Phylogenetic Variational Inference Organization". Could also do .net and "Network."

**Comment by zcrabbit** [comment]
I like it!
