### ISSUE TITLE
Include primary subsplit pairs (PSPs) in indexing setup

### ISSUE THREAD

**Issue by matsen** [phylovi/libsbn#95]
For any tree in the support of an indexer, we should be able to get information that will allow us to get the PSP of that edge. Specifically, I propose returning the index of the corresponding parent-child subsplit pair in the indexer (aka the ParamParser).

We will need to make some conventions about which parent-child subsplit pair is used in the case of interior edges.

Reference:

![image](https://user-images.githubusercontent.com/112708/62868762-3845eb00-bccb-11e9-9291-581651df9545.png)

**Comment by zcrabbit** [comment]
These are the indexes we need for branch length parameterization. Similar to subsplit pairs (which are for SBN parameterization), we need to construct another dictionary of splits (or root subsplits) and primary subsplit pairs with index values. The entire set up would be similar to what we did for subsplit pairs. For each tree, we loop over the edges to grab the corresponding indexes.

**Comment by matsen** [comment]
@zcrabbit , thanks for the note. 

Given that PSPs are parent-child subsplit pairs (PCSSs), won't they already be keys of the the indexer? Of course, we have to have every PCSS for every rooting, and it seems to be that each PSP will be a PCSS for some rooting of the tree.

If so, it would seem cleaner to just return the indices in the current indexing system.

**Comment by zcrabbit** [comment]
Yes, but we need a new set of indices for the branch length parameterization. Please see my vbpi code for reference.

**Comment by matsen** [comment]
In the VBPI code, you parameterize things like the location of the branch length distribution with lines such as
```
self.get_loc(split) + np.sum([self.get_loc(subsplit) for subsplit in subsplit_pair[split]])
```
We already have an indexing setup for splits (the rootsplits) and for all the subsplits. For each edge of every tree, I propose returning a triple of `split_index`, `left_subsplit_index`, `right_subsplit_index`. You can use these to index an array or dictionary in a way very similar to what you are doing now, like:
```
split_loc_array[split_index] + subsplit_loc_array[left_subsplit_index] + subsplit_loc_array[right_subsplit_index]
```
for example to get the location parameter for that branch.

This has the advantage that there is only one indexing system rather than two that refer to fundamentally the same things.
